SURF_SPOT_NAMES: set[str] = {
    "Mundaka",
    "Zarautz",
    "La Zurriola",
    "Sopelana",
    "Barinatxe",
    "Ereaga",
    "Meñakoz",
    "Punta Galea",
    "Bakio",
    "Deba",
    "Getaria / Orrua",
    "Erretegia",
    "Somo",
    "Liencres (Valdearenas)",
    "Los Locos (Suances)",
    "El Brusco (Noja)",
    "Santa Marina",
    "Laredo",
    "Sardinero",
    "Gerra",
    "Oyambre",
    "Rodiles",
    "Salinas",
    "Xagó",
    "San Lorenzo (Gijón)",
    "Vega",
    "San Antolín",
    "Santa Marina (Ribadesella)",
    "Tapia de Casariego / Anguileiro",
    "Côte des Basques",
    "Grande Plage",
    "Parlementia",
    "Hendaye",
}
